"""Apply a restructure plan by moving files.

Safe by default:
- Use --dry-run to preview.
- Does not modify note contents or update wiki links.

This script expects the JSON plan generated by build_restructure_plan.py.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


def load_plan(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8", errors="replace"))


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def move_file(src: Path, dst: Path, *, dry_run: bool, overwrite: bool) -> None:
    if not src.exists():
        print(f"WARN missing source: {src}")
        return

    ensure_dir(dst.parent)

    if dst.exists():
        if not overwrite:
            print(f"WARN destination exists, skip (use --overwrite): {dst}")
            return
        if dry_run:
            print(f"DRYRUN overwrite: {src} -> {dst}")
            return
        dst.unlink()

    if dry_run:
        print(f"DRYRUN move: {src} -> {dst}")
        return

    shutil.move(str(src), str(dst))
    print(f"MOVED: {src} -> {dst}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plan", required=True, help="Path to plan JSON")
    parser.add_argument("--vault-root", default=str(Path.cwd()), help="Vault root directory")
    parser.add_argument("--dry-run", action="store_true", help="Preview moves without changing files")
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow overwriting destination files if they already exist",
    )

    args = parser.parse_args()
    plan_path = Path(args.plan).expanduser()
    vault_root = Path(args.vault_root).expanduser().resolve()

    if not plan_path.exists():
        raise SystemExit(f"Plan not found: {plan_path}")

    plan = load_plan(plan_path)
    notes = plan.get("notes", [])

    for n in notes:
        src_rel = n.get("source")
        dst_rel = n.get("destination")
        if not isinstance(src_rel, str) or not isinstance(dst_rel, str):
            continue

        src = vault_root / Path(src_rel)
        dst = vault_root / Path(dst_rel)
        move_file(src, dst, dry_run=bool(args.dry_run), overwrite=bool(args.overwrite))

    print("Done. Review for broken links and update MOCs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
